### ISSUE TITLE
Question: does one need to manually update the SOA after a zone update?

### ISSUE THREAD

**Issue by hostingnuggets** [silkeh/ruby-pdns_api#5]
I am asking myself it this PDNS API does automatically update the serial number in the SOA after an update of the zone? I could not find anything in the code.

This would mean one needs to manually update the serial in the SOA for the changes to be effecitve, is this correct?

**Comment by silkeh** [comment]
This can be configured in the zone settings, see `soa_edit` and `soa_edit_api` in the [API documentation](https://doc.powerdns.com/md/httpapi/api_spec/#zones), and the `SOA-EDIT` and `SOA-EDIT-API` metadata settings. This is currently not exposed in this library, but can be set manually with something like:
```
pdnsutil set-meta [zone] SOA-EDIT-API INCEPTION-INCREMENT
```

**Comment by hostingnuggets** [comment]
Thank you for the hint, for now I will then manually update the SOA record in my own code.
